# Generated by Django 3.0 on 2019-12-23 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(default='_', max_length=128, unique=True)),
                ('markdown_field', models.TextField(blank=True, null=True)),
                ('html_field', models.TextField(blank=True, null=True)),
                ('convetr_md_to_html', models.BooleanField(default=False)),
                ('is_adopted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Committeeman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=128, unique=True)),
                ('signature', models.CharField(db_index=True, max_length=128, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committeeman', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ManyToManyField(blank=True, related_name='committeeman', to='committee.Applicant')),
            ],
        ),
    ]
