# Generated by Django 3.0 on 2019-12-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_applicant_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
