# Generated by Django 3.0 on 2019-12-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(default=' ', max_length=128, unique=True)),
                ('markdown_field', models.TextField(blank=True, null=True)),
                ('html_field', models.TextField(editable=False)),
                ('destination', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(default=' ', max_length=128, unique=True)),
                ('markdown_field', models.TextField(blank=True, null=True)),
                ('html_field', models.TextField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(default=' ', max_length=128, unique=True)),
                ('markdown_field', models.TextField(blank=True, null=True)),
                ('html_field', models.TextField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(default=' ', max_length=128, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='info/gallery/%Y/%m/%d')),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='info.Info')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='info.Location')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='info.Participant')),
            ],
        ),
    ]
