# Generated by Django 3.0 on 2019-12-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='_', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='slug',
            field=models.SlugField(default='_', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(default='_', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='slug',
            field=models.SlugField(default='_', max_length=128, unique=True),
        ),
    ]
