# Generated by Django 3.0 on 2019-12-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_gallery_remote_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(default='_', max_length=128, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='info/gallery/%Y/%m/%d')),
                ('remote_img', models.CharField(blank=True, max_length=256, null=True)),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='info.Info')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='info.Location')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='info.Participant')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
